 version: 2.1
 orbs:
   slack: circleci/slack@4.1.4
   terraform: circleci/terraform@3.1.0
 jobs:
    check-terraform-plan:
      executor: terraform/default
      steps:
        - checkout
        - terraform/init:
            backend: true
            backend_config_file: backend.hcl
            path: .
        - terraform/validate:
            path: .
        - terraform/plan:
            context: terraform
            persist-workspace: true
            backend_config_file: backend.hcl
            requires:
            - terraform/init
            path: .

      working_directory: ~/src
   
    deploy:
     docker:
       - image: cimg/base:stable
     steps:
       - run: echo "deploy my app"
       # In the event the deployment has failed, alert the engineering team
       - slack/notify:
           event: fail
           template: basic_fail_1
           mentions: "@EngineeringTeam"
       # When there is a successful deployment, send a notification with a different template.
       - slack/notify:
           event: pass
           template: success_tagged_deploy_1


 workflows:
   test-and-deploy:
     jobs:
       - check-terraform-plan

       - slack/on-hold:
          context:
            - slack-api
          requires:
            - check-terraform-plan
          filters:
            branches:
              only: 
                - main

       - pause_workflow:
          type: approval
          requires:
            - check-terraform-plan
            - slack/on-hold
          filters:
            branches:
              only: 
                - main

       - deploy:
          context:
            - slack-api
          requires:
            - pause_workflow
          filters:
            branches:
              only: 
                - main